### ISSUE TITLE
Add option to alias branches to different domains

### ISSUE THREAD

**Issue by mxstbr** [siddharthkp/now-cd#7]
We have a `production` branch which we'd like to alias to `spectrum.chat`. I'm imagining something like this maybe?

```
npx now-cd --alias "production=spectrum.chat" --alias "staging=staging.spectrum.chat"
```

https://github.com/siddharthkp/now-cd/blob/fa6546e6651ad8ef090501ddd2416cde9b7d2675/index.js#L18-L21

**Comment by siddharthkp** [comment]
Just curious, would you still need a dedicated `staging` when all of your pull requests have a staging?
